version: '3.3'
services:
  api_zachs_memes:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: api-zachmemes
    restart: unless-stopped
    ports:
      - 9786:3000
  site_zachs_memes:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: site-zachmemes
    restart: unless-stopped
    ports:
      - 9787:3000